// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

public class LoginResponse {
    private String token;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getToken() {
        return this.token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setToken(final String token) {
        this.token = token;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LoginResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LoginResponse(final String token) {
        this.token = token;
    }
}
