// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

public class LoginRequest {
    private String login;
    private String password;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogin() {
        return this.login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogin(final String login) {
        this.login = login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LoginRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LoginRequest(final String login, final String password) {
        this.login = login;
        this.password = password;
    }
}
