// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;

public class MoveRequest {
    private String src;
    private String dst;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSrc() {
        return this.src;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDst() {
        return this.dst;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSrc(final String src) {
        this.src = src;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDst(final String dst) {
        this.dst = dst;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MoveRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MoveRequest(final String src, final String dst) {
        this.src = src;
        this.dst = dst;
    }
}
