// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

public class NewUserRequest {
    private String login;
    private String password;
    private Boolean isAdmin;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogin() {
        return this.login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogin(final String login) {
        this.login = login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsAdmin(final Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NewUserRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public NewUserRequest(final String login, final String password, final Boolean isAdmin) {
        this.login = login;
        this.password = password;
        this.isAdmin = isAdmin;
    }
}
