// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;
import java.util.UUID;

public class ProjectResponse {
    private UUID id;
    private String name;
    private java.util.List<UserSummaryResponse> members; //might or might not work, did not test :/
    private UserSummaryResponse owner;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.util.List<UserSummaryResponse> getMembers() {
        return this.members;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserSummaryResponse getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMembers(final java.util.List<UserSummaryResponse> members) {
        this.members = members;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOwner(final UserSummaryResponse owner) {
        this.owner = owner;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProjectResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ProjectResponse(final UUID id, final String name, final java.util.List<UserSummaryResponse> members, final UserSummaryResponse owner) {
        this.id = id;
        this.name = name;
        this.members = members;
        this.owner = owner;
    }
}
