// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;
import java.util.UUID;

public class UpdateProjectRequest {
    private String name;
    private UUID newOwnerId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getNewOwnerId() {
        return this.newOwnerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setNewOwnerId(final UUID newOwnerId) {
        this.newOwnerId = newOwnerId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UpdateProjectRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UpdateProjectRequest(final String name, final UUID newOwnerId) {
        this.name = name;
        this.newOwnerId = newOwnerId;
    }
}
