// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;
import java.util.UUID;

public class UserResponse {
    private UUID id;
    private String login;
    private String displayName;
    private Boolean isAdmin;
    private String avatar;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogin() {
        return this.login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDisplayName() {
        return this.displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogin(final String login) {
        this.login = login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayName(final String displayName) {
        this.displayName = displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsAdmin(final Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserResponse(final UUID id, final String login, final String displayName, final Boolean isAdmin, final String avatar) {
        this.id = id;
        this.login = login;
        this.displayName = displayName;
        this.isAdmin = isAdmin;
        this.avatar = avatar;
    }
}
