// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;
import java.util.UUID;

public class UserProjectRequest {
    private UUID userId;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setUserId(final UUID userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProjectRequest() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserProjectRequest(final UUID userId) {
        this.userId = userId;
    }
}
