// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.dto;

import lombok.*;
import java.util.UUID;

public class UserSummaryResponse {
    private UUID id;
    private String displayName;
    private String avatar;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDisplayName() {
        return this.displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayName(final String displayName) {
        this.displayName = displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserSummaryResponse() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserSummaryResponse(final UUID id, final String displayName, final String avatar) {
        this.id = id;
        this.displayName = displayName;
        this.avatar = avatar;
    }
}
