// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.model;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "projects")
public class ProjectModel extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @Column(nullable = false)
    private String name;
    @Column(nullable = false)
    private String path;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "owner_id", nullable = false, referencedColumnName = "id")
    private UserModel owner;
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "project_members", joinColumns = @JoinColumn(name = "project_id"), inverseJoinColumns = @JoinColumn(name = "user_id"))
    private List<UserModel> members = new ArrayList<>(); //Moulinette was expeecting List

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPath() {
        return this.path;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UserModel getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<UserModel> getMembers() {
        return this.members;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPath(final String path) {
        this.path = path;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOwner(final UserModel owner) {
        this.owner = owner;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMembers(final List<UserModel> members) {
        this.members = members;
    }
}
