// Generated by delombok at Tue Jun 24 13:03:41 CEST 2025
package fr.epita.assistants.ping.data.model;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

@Entity
@Table(name = "users")
public class UserModel extends PanacheEntityBase {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @Column(unique = true, nullable = false)
    private String login;
    @Column(nullable = false)
    private String password;
    @Column(name = "display_name")
    private String displayName;
    private String avatar;
    @Column(name = "is_admin")
    private Boolean isAdmin = false;
    @ManyToMany(mappedBy = "members", fetch = FetchType.LAZY)
    private Set<ProjectModel> memberProjects = new HashSet<>();
    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY)
    private Set<ProjectModel> ownedProjects = new HashSet<>();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public UUID getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLogin() {
        return this.login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDisplayName() {
        return this.displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<ProjectModel> getMemberProjects() {
        return this.memberProjects;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Set<ProjectModel> getOwnedProjects() {
        return this.ownedProjects;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final UUID id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLogin(final String login) {
        this.login = login;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDisplayName(final String displayName) {
        this.displayName = displayName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setIsAdmin(final Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMemberProjects(final Set<ProjectModel> memberProjects) {
        this.memberProjects = memberProjects;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setOwnedProjects(final Set<ProjectModel> ownedProjects) {
        this.ownedProjects = ownedProjects;
    }
}
